TRUNCATE TABLE COMMANDE;
TRUNCATE TABLE FOURNI;
TRUNCATE TABLE ARTICLE;
TRUNCATE TABLE FOURNISSEUR;

INSERT INTO UML.ARTICLE(NOM,QUANTITE,PRIX,CODEBARRE,SEUILDEREASSORTIMENT,TYPEDEVENTE) VALUES ('Celeron J1750',10,72,000000,5, FALSE);
INSERT INTO UML.ARTICLE(NOM,QUANTITE,PRIX,CODEBARRE,SEUILDEREASSORTIMENT,TYPEDEVENTE) VALUES ('Celeron J1800',14,72,000001,8, FALSE);
INSERT INTO UML.ARTICLE(NOM,QUANTITE,PRIX,CODEBARRE,SEUILDEREASSORTIMENT,TYPEDEVENTE) VALUES ('Celeron J1850',5,82,000010,10, FALSE);
INSERT INTO UML.ARTICLE(NOM,QUANTITE,PRIX,CODEBARRE,SEUILDEREASSORTIMENT,TYPEDEVENTE) VALUES ('Celeron J1900',10,82,000011,7, FALSE);
INSERT INTO UML.ARTICLE(NOM,QUANTITE,PRIX,CODEBARRE,SEUILDEREASSORTIMENT,TYPEDEVENTE) VALUES ('Celeron J2850',15,82,000100,10, FALSE);
INSERT INTO UML.ARTICLE(NOM,QUANTITE,PRIX,CODEBARRE,SEUILDEREASSORTIMENT,TYPEDEVENTE) VALUES ('Celeron J2900',20,94,000101,7, FALSE);
INSERT INTO UML.ARTICLE(NOM,QUANTITE,PRIX,CODEBARRE,SEUILDEREASSORTIMENT,TYPEDEVENTE) VALUES ('Celeron N2805',25,107,000110,20, FALSE);
INSERT INTO UML.ARTICLE(NOM,QUANTITE,PRIX,CODEBARRE,SEUILDEREASSORTIMENT,TYPEDEVENTE) VALUES ('Celeron N2806',20,107,000111,20, FALSE);
INSERT INTO UML.ARTICLE(NOM,QUANTITE,PRIX,CODEBARRE,SEUILDEREASSORTIMENT,TYPEDEVENTE) VALUES ('Celeron N2807',18,107,001000,15, FALSE);
INSERT INTO UML.ARTICLE(NOM,QUANTITE,PRIX,CODEBARRE,SEUILDEREASSORTIMENT,TYPEDEVENTE) VALUES ('Celeron N2808',19,107,001001,22, FALSE);
INSERT INTO UML.ARTICLE(NOM,QUANTITE,PRIX,CODEBARRE,SEUILDEREASSORTIMENT,TYPEDEVENTE) VALUES ('Celeron N2810',9,107,001010,13, FALSE);
INSERT INTO UML.ARTICLE(NOM,QUANTITE,PRIX,CODEBARRE,SEUILDEREASSORTIMENT,TYPEDEVENTE) VALUES ('Celeron N2815',15,107,001011,20, FALSE);

INSERT INTO UML.ARTICLE(NOM,QUANTITE,PRIX,CODEBARRE,SEUILDEREASSORTIMENT,TYPEDEVENTE) VALUES ('Athlon 5350',32,59,001100,18, FALSE);
INSERT INTO UML.ARTICLE(NOM,QUANTITE,PRIX,CODEBARRE,SEUILDEREASSORTIMENT,TYPEDEVENTE) VALUES ('Athlon 5150',24,49,001101,14, FALSE);
INSERT INTO UML.ARTICLE(NOM,QUANTITE,PRIX,CODEBARRE,SEUILDEREASSORTIMENT,TYPEDEVENTE) VALUES ('Sempron 3850',18,39,001110,13, FALSE);
INSERT INTO UML.ARTICLE(NOM,QUANTITE,PRIX,CODEBARRE,SEUILDEREASSORTIMENT,TYPEDEVENTE) VALUES ('Sempron 2650',13,34,001111,15, FALSE);

INSERT INTO UML.FOURNISSEUR(NOM,ADRESSE,CODEPOSTAL,NUMEROTELEPHONE) VALUES ('Intel','Santa Clara, California',95050,1234567890);
INSERT INTO UML.FOURNISSEUR(NOM,ADRESSE,CODEPOSTAL,NUMEROTELEPHONE) VALUES ('AMD','Sunnyvale, California',94085,1234567899);

INSERT INTO UML.FOURNI(ID_ARTICLE,ID_FOURNISSEUR) VALUES (1,1);
INSERT INTO UML.FOURNI(ID_ARTICLE,ID_FOURNISSEUR) VALUES (2,1);
INSERT INTO UML.FOURNI(ID_ARTICLE,ID_FOURNISSEUR) VALUES (3,1);
INSERT INTO UML.FOURNI(ID_ARTICLE,ID_FOURNISSEUR) VALUES (4,1);
INSERT INTO UML.FOURNI(ID_ARTICLE,ID_FOURNISSEUR) VALUES (5,1);
INSERT INTO UML.FOURNI(ID_ARTICLE,ID_FOURNISSEUR) VALUES (6,1);
INSERT INTO UML.FOURNI(ID_ARTICLE,ID_FOURNISSEUR) VALUES (7,1);
INSERT INTO UML.FOURNI(ID_ARTICLE,ID_FOURNISSEUR) VALUES (8,1);
INSERT INTO UML.FOURNI(ID_ARTICLE,ID_FOURNISSEUR) VALUES (9,1);
INSERT INTO UML.FOURNI(ID_ARTICLE,ID_FOURNISSEUR) VALUES (10,1);
INSERT INTO UML.FOURNI(ID_ARTICLE,ID_FOURNISSEUR) VALUES (11,1);
INSERT INTO UML.FOURNI(ID_ARTICLE,ID_FOURNISSEUR) VALUES (12,1);
INSERT INTO UML.FOURNI(ID_ARTICLE,ID_FOURNISSEUR) VALUES (13,2);
INSERT INTO UML.FOURNI(ID_ARTICLE,ID_FOURNISSEUR) VALUES (14,2);
INSERT INTO UML.FOURNI(ID_ARTICLE,ID_FOURNISSEUR) VALUES (15,2);
INSERT INTO UML.FOURNI(ID_ARTICLE,ID_FOURNISSEUR) VALUES (16,2);

INSERT INTO UML.COMMANDE(ID_ARTICLE,QUANTITE,DATE_COMMANDE,MONTANT) VALUES (3,2,'2014/11/30 15:15:15',164);
INSERT INTO UML.COMMANDE(ID_ARTICLE,QUANTITE,DATE_COMMANDE,MONTANT) VALUES (2,5,'2014/11/31 16:16:16',360);