DROP TABLE FOURNI;
DROP TABLE COMMANDE;
DROP TABLE FOURNISSEUR;
DROP TABLE ARTICLE;

CREATE TABLE UML.ARTICLE (
ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
NOM VARCHAR(255) NOT NULL,
QUANTITE INTEGER NOT NULL,
PRIX DOUBLE NOT NULL,
CODEBARRE INTEGER NOT NULL,
SEUILDEREASSORTIMENT INTEGER NOT NULL,
TYPEDEVENTE BOOLEAN NOT NULL,
PRIMARY KEY (ID) );

CREATE TABLE UML.FOURNISSEUR (
ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
NOM VARCHAR(255) NOT NULL,
ADRESSE VARCHAR(255) NOT NULL,
CODEPOSTAL INTEGER NOT NULL,
NUMEROTELEPHONE INTEGER NOT NULL,
PRIMARY KEY (ID) );

CREATE TABLE UML.COMMANDE (
ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
ID_ARTICLE INTEGER NOT NULL,
QUANTITE INTEGER NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY("ID_ARTICLE") REFERENCES ARTICLE ("ID")
);

CREATE TABLE UML.FOURNI (
ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
ID_ARTICLE INTEGER NOT NULL,
ID_FOURNISSEUR INTEGER NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY("ID_ARTICLE") REFERENCES ARTICLE ("ID"),
FOREIGN KEY("ID_FOURNISSEUR") REFERENCES FOURNISSEUR ("ID")
);