package stockgestion.UI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import stockgestion.Controlleur.FournisseurControlleur;
import stockgestion.Entite.Fournisseur;
import stockgestion.Outil.Verificateur;

public class NouveauFournisseur extends javax.swing.JFrame {
    private static NouveauFournisseur instance = null;
    private JFrame previousFrame;

    private NouveauFournisseur() {
        initComponents();
        addActionListeners();
        setTitle("Nouveau fournisseur");
    }
    
    public static NouveauFournisseur getInstance(){
        if(instance == null){
            instance = new NouveauFournisseur();
        }
        return instance;
    }
    
    private void addActionListeners(){
        back.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                NouveauFournisseur.this.setVisible(false);
                previousFrame.setVisible(true);
            }
        });
        
        ajouter.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                //Ajouter un fournisseur dans la BDD
                if(Verificateur.isValideFournisseur(nom, adresse, codePostal, numTel)){
                    Fournisseur fournisseur = new Fournisseur();
                    fournisseur.setNom(nom.getText());
                    fournisseur.setAdresse(adresse.getText());
                    fournisseur.setCodePostal(Integer.parseInt(codePostal.getText()));
                    fournisseur.setNumeroTelephone(Integer.parseInt(numTel.getText()));

                    FournisseurControlleur.getInstance().ajouter(fournisseur);

                    //Remettre a zero les champs
                    resetUI();

                    //Rafraichir la liste des fournisseurs puis retourner a la fenetre Ajout article
                    stockgestion.StockGestion.getInstance().refreshUI();
                    NouveauFournisseur.this.setVisible(false);
                    previousFrame.setVisible(true);
                }                
            }
        });
    }
    
    public void setPreviousWindow(JFrame frame){
        this.previousFrame = frame;
    }
    
    private void resetUI(){
        nom.setText("");
        adresse.setText("");
        codePostal.setText("");
        numTel.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomLabel = new javax.swing.JLabel();
        adresseLabel = new javax.swing.JLabel();
        codePostalLabel = new javax.swing.JLabel();
        numTelLabel = new javax.swing.JLabel();
        adresse = new javax.swing.JTextField();
        codePostal = new javax.swing.JTextField();
        numTel = new javax.swing.JTextField();
        nom = new javax.swing.JTextField();
        ajouter = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nomLabel.setText("Nom");

        adresseLabel.setText("Adresse");

        codePostalLabel.setText("Code postal");

        numTelLabel.setText("Numéro de téléphone");

        ajouter.setText("Ajouter");

        back.setText("Retourner");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(240, 240, 240)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(adresseLabel)
                                .addComponent(nomLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(adresse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(152, 152, 152)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(codePostalLabel)
                                    .addGap(28, 28, 28)
                                    .addComponent(codePostal, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(numTelLabel)
                                    .addGap(28, 28, 28)
                                    .addComponent(numTel, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomLabel)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adresseLabel)
                    .addComponent(adresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codePostalLabel)
                    .addComponent(codePostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numTelLabel)
                    .addComponent(numTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adresse;
    private javax.swing.JLabel adresseLabel;
    private javax.swing.JButton ajouter;
    private javax.swing.JButton back;
    private javax.swing.JTextField codePostal;
    private javax.swing.JLabel codePostalLabel;
    private javax.swing.JTextField nom;
    private javax.swing.JLabel nomLabel;
    private javax.swing.JTextField numTel;
    private javax.swing.JLabel numTelLabel;
    // End of variables declaration//GEN-END:variables
}
